/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Shoes.gltf --transform 
Files: Shoes.gltf [38.67MB] > C:\Users\ASUS\Downloads\Shoes\Shoes-transformed.glb [1.39MB] (96%)
Author: grafi (https://sketchfab.com/zdenkoroman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/puma-shoe-purple-3d-scan-a6d4580e699c4fa1a5967dff3cd4609f
Title: Puma Shoe Purple 3D Scan
*/

import React from 'react'
import * as THREE from "three"
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Shoes-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.Object_2.geometry} 
        material={materials['default']} 
        position={[0.011, -0.046, 0.046]} 
        rotation={[0, -0, 0]}/>
      <mesh geometry={nodes.Object_2.geometry} material={materials['default']} position={[0.011, -0.046, 0.046]} rotation={[0, -0.005, -3.111]} >
        <meshStandardMaterial
          color="black"
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/Shoes-transformed.glb')
